//
//  Random.h
//  RayTracer
//
//  Created by WangYue on 2016-11-02.
//  Copyright © 2016 WangYue. All rights reserved.
//

#ifndef Random_h
#define Random_h
/*
// Use boost random library

#include <boost/format.hpp>
#include <boost/random.hpp>
double randf(void)
{
    boost::mt19937 rng(67);
    static boost::uniform_01<boost::mt19937> zeroone(rng);
    return zeroone();
}

*/
#include <cmath>
#include <random>

double randf(void)
{
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(0.0, 1.0);
    //Use dis to transform the random unsigned int generated by gen into a double in [1, 2)
    //Each call to dis(gen) generates a new random double
    return dis(gen);
}

#endif /* Random_h */
